"""
    Put your test data for tests here.

"""

TEST_ORG_DATA = {
 'login': 'github',
 'id': 9919,
 'node_id': 'MDEyOk9yZ2FuaXphdGlvbjk5MTk=',
 'url': 'https://api.github.com/orgs/github',
 'repos_url': 'https://api.github.com/orgs/github/repos',
 'events_url': 'https://api.github.com/orgs/github/events',
 'hooks_url': 'https://api.github.com/orgs/github/hooks',
 'issues_url': 'https://api.github.com/orgs/github/issues',
 'members_url': 'https://api.github.com/orgs/github/members{/member}',
 'public_members_url': 'https://api.github.com/orgs/github/public_members{/member}',
 'avatar_url': 'https://avatars1.githubusercontent.com/u/9919?v=4',
 'description': 'How people build software.',
 'name': 'GitHub',
 'company': None,
 'blog': 'https://github.com/about',
 'location': 'San Francisco, CA',
 'email': 'support@github.com',
 'is_verified': True,
 'has_organization_projects': True,
 'has_repository_projects': True,
 'public_repos': 297,
 'public_gists': 0,
 'followers': 0,
 'following': 0,
 'html_url': 'https://github.com/github',
 'created_at': '2008-05-11T04:37:31Z',
 'updated_at': '2019-04-23T15:59:14Z',
 'type': 'Organization'
 }

TEST_REPO_DATA = [
    {
        'id': 15929,
        'node_id': 'MDEwOlJlcG9zaXRvcnkxNTkyOQ==',
        'name': 'albino',
        'full_name': 'github/albino',
        'private': False,
        'fork': False,
        'url': 'https://api.github.com/repos/github/albino',
        'created_at': '2008-05-11T04:45:03Z',
        'updated_at': '2019-02-14T20:41:00Z',
        'pushed_at': '2017-08-06T10:00:06Z',
        'size': 156,
        'stargazers_count': 222,
        'watchers_count': 222,
        'language': 'Ruby',
        'has_issues': True,
        'has_projects': True,
        'default_branch': 'master',
        'permissions': {'admin': False, 'push': False, 'pull': True}
    },
    {
        'id': 15930,
        'node_id': 'MDEwOlJlcG9zaXRvcnkxNTkyOQ==',
        'name': 'parser',
        'full_name': 'github/parser',
        'private': False,
        'fork': False,
        'url': 'https://api.github.com/repos/github/parser',
        'created_at': '2008-05-11T04:45:03Z',
        'updated_at': '2019-02-14T20:41:00Z',
        'pushed_at': '2017-08-06T10:00:06Z',
        'size': 156,
        'stargazers_count': 222,
        'watchers_count': 101,
        'language': 'Python',
        'has_issues': True,
        'has_projects': True,
        'default_branch': 'master',
        'permissions': {'admin': False, 'push': False, 'pull': True}
    },
    {
        'id': 15931,
        'node_id': 'MDEwOlJlcG9zaXRvcnkxNTkyOQ==',
        'name': 'analyzer',
        'full_name': 'github/analyzer',
        'private': False,
        'fork': True,
        'url': 'https://api.github.com/repos/github/analyzer',
        'created_at': '2008-05-11T04:45:03Z',
        'updated_at': '2019-02-14T20:41:00Z',
        'pushed_at': '2017-08-06T10:00:06Z',
        'size': 156,
        'stargazers_count': 222,
        'watchers_count': 719,
        'language': 'Python',
        'has_issues': True,
        'has_projects': True,
        'default_branch': 'master',
        'permissions': {'admin': False, 'push': False, 'pull': True}
    },
    
]